### PR TITLE
Preventing compile errors.

### PR DESCRIPTION
**Pull request by thiagoquinelato**

### CODE REVIEW

**Comment by philippedevloo** [comment]
Have you checked the compilation on a linux or windows machine? As there are lapack/blas calls in the code, shouldn't you include lapack or blas is the operating system is not MacOS?

**Comment by philippedevloo** [comment]
Tentei responder do jeito que posso..

Philippe Devloo
phil@fec.unicamp.br

**Comment by thiagoquinelato** [comment]
The checks on all platforms are in progress. Only when all of them pass we can merge this pull request. 
Currently, there's no CTest configuration using LAPACK/BLAS. Perhaps we should install this library on the test hosts and write a CTest configuration to check if this code will fail (I believe it will). This would be another task. Feel free to open an issue to address it.

**Comment by philippedevloo** [comment]
There are CTests that depend on Lapack. All the tests that validate the computation of eigenvalues will only execute is LAPACK is installed and "active". Francisco knows all about it...

**Comment by thiagoquinelato** [comment]
Hmm... I was pretty sure none of the CTest configs we are executing daily was using LAPACK/BLAS... Please, @orlandini , enlighten us with your knowledge about that.

**Comment by orlandini** [comment]
@philippedevloo , 
none of the CTest configs currently enables LAPACK. The name ALL_FLAGS_ON may be misleading, since it turns on only a few flags... Therefore, the unit test that tests LAPACK (TestMatrix) will be executed, but all the code that refers to LAPACK won't be executed, since it's between:

    #ifdef USING_LAPACK
    ...code here...
    #endif


Sorry if this was exactly what you meant by _All the tests that validate the computation of eigenvalues will only execute is LAPACK is installed and "active"_, but I wanted to be sure that we're on the same page!

I do agree we need to improve the unit tests, and testing LAPACK is one of the things we must to do. But currently it is not being done.

**Comment by philippedevloo** [comment]
Please task Luiz Marques to include lapack in the test suites

**Pull request merged**
