### PR TITLE
Create initializer list constructor and assignment operators to the TPZVec and TPZFMatrix classes

### PR DESCRIPTION
**Pull request by AndradeL**

### CODE REVIEW

**Comment by philippedevloo** [comment]
It is not clear to me whether initializing a matrix with a single list will create a column matrix (size,1) or a row matrix (1,size).
I definitely believe it should create a column matrix.

**Comment by AndradeL** [comment]
Which one should it be?
If I create with a list of 5 elements, should the matrix have 5 columns or 5 rows?

**Comment by philippedevloo** [comment]
It should definitely be 5 rows

Philippe Devloo
phil@fec.unicamp.br

**Comment by luizcmarques** [comment]
Everything ok with this request: I ran a local merge with master, built and compiled everything , including Projects with no error. Pull request approved.

**Pull request merged**
