### PR TITLE
GenGrid3D bugfix

### PR DESCRIPTION
**Pull request by PedroLima92**
`TPZGenGrid3D` had multiple elements with negative `detjac`.
It was also kinda complicated for me to read, so I went ahead and rewrote some of it in a way I think is more readable.
Everything is mostly working fine now, but HCurl unit test is breaking for prismatic elements.

@orlandini can you take a look and see if it's a quick fix?

I've also added a UnitTest on my way here

### CODE REVIEW

**Comment by orlandini** [comment]
Please, set it as draft so it doesn't get merged by accident.

In which commit exactly the HCurl unit test started breaking?

**Comment by PedroLima92** [comment]
> In which commit exactly the HCurl unit test started breaking?

commit b7b092f

**Comment by orlandini** [comment]
@PedroLima92 this refactor has revealed a bug in the prismatic elements. I don't have time for fixing it now, so we will skip this test for now and  i've updated issue #76 to at least track it. Thanks for reporting it.

**Review by orlandini — COMMENTED** [review]
It seems good to me. I've added a unit test for gengrid2d as well.

**Comment by PedroLima92** [comment]
Great! Thanks a lot for the help! :smile:

**Pull request merged**
